import '../App.css';
import './Legal.css';

export function PrivacyPolicy() {
    return (
        <div className="page">
            <div className="page-content">
                <div className="legal-page">
                    <div className="legal-content">
                        <h1>Privacy Policy</h1>
                        <span className="legal-update-date">Last Updated: January 7, 2026</span>

                        <p>
                            At Mr. Food, we are committed to protecting the privacy and security of our clients, their employees, and the data generated by our robotic systems. This Privacy Policy outlines how we collect, use, and safeguard information when you use our automated kitchen solutions and software platforms.
                        </p>

                        <h2>1. Information We Collect</h2>
                        <p>
                            We collect data necessary to operate, maintain, and improve our robotic systems:
                        </p>
                        <ul>
                            <li><strong>Operational Data:</strong> Throughput rates, error logs, cooking times, and ingredient usage statistics generated by our robots.</li>
                            <li><strong>Sensor Data:</strong> Images, video feeds, and depth data captured by the robot's perception systems to enable navigation and manipulation.</li>
                            <li><strong>Usage Data:</strong> Information about how your staff interacts with our software interfaces and control panels.</li>
                            <li><strong>Account Information:</strong> Business contact details, billing information, and location data for your kitchens.</li>
                        </ul>

                        <h2>2. How We Use Your Data</h2>
                        <p>
                            The data collected is primarily used to:
                        </p>
                        <ul>
                            <li><strong>Ensure Reliability:</strong> Monitor system health and predict maintenance needs before failures occur.</li>
                            <li><strong>Improve Performance:</strong> Train our computer vision and motion planning models to handle new ingredients and edge cases.</li>
                            <li><strong>Provide Analytics:</strong> Generate dashboards and reports for your team regarding efficiency, waste, and yield.</li>
                            <li><strong>Safety & Compliance:</strong> Verify adherence to food safety protocols (e.g., cooking temperatures).</li>
                        </ul>

                        <h2>3. Data Sharing and Security</h2>
                        <p>
                            We do not sell your operational data. We may share aggregated, anonymized insights (e.g., "industry-wide burger flip speeds") but never specific proprietary data from your kitchen.
                        </p>
                        <p>
                            We implement industry-standard encryption and security protocols to protect data both in transit and at rest. Access to raw sensor data is strictly limited to engineering teams for debugging and model training purposes.
                        </p>

                        <h2>4. Contact Us</h2>
                        <p>
                            If you have questions about our data practices, please contact us at <a href="mailto:privacy@mrfood.ai">privacy@mrfood.ai</a>.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
